/**
 * Country dial codes (E.164 country calling codes) and the IANA-zone hints used
 * to preselect one.
 *
 * Auto-send texts go out through Twilio, which is now provisioned beyond the
 * US/CA — so a number typed without a country code can no longer be assumed to
 * be +1. Every phone field in the app and on the site pairs a country picker
 * with the national number and stores the combined E.164 string, which is the
 * only format Twilio (and the `sms:` greeting shortcut) accept reliably.
 *
 * Mirrored across backend / app / website - same as `lib/phone.ts`. Keep the
 * three copies in step.
 */

export interface Country {
  /** ISO 3166-1 alpha-2, e.g. "IN". Also the picker's option value. */
  code: string;
  name: string;
  /** E.164 country calling code WITHOUT the leading "+", e.g. "91". */
  dial: string;
  /**
   * True for the country a shared dial code resolves back to when parsing a
   * stored number (e.g. "+1" -> US, not Canada; "+7" -> Russia, not Kazakhstan).
   * Only the dial code is ever sent, so the choice is cosmetic.
   */
  primary?: boolean;
}

/** Every selectable country, sorted by name (the picker renders them in order). */
export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", dial: "93", primary: true },
  { code: "AL", name: "Albania", dial: "355", primary: true },
  { code: "DZ", name: "Algeria", dial: "213", primary: true },
  { code: "AD", name: "Andorra", dial: "376", primary: true },
  { code: "AO", name: "Angola", dial: "244", primary: true },
  { code: "AG", name: "Antigua & Barbuda", dial: "1" },
  { code: "AR", name: "Argentina", dial: "54", primary: true },
  { code: "AM", name: "Armenia", dial: "374", primary: true },
  { code: "AW", name: "Aruba", dial: "297", primary: true },
  { code: "AU", name: "Australia", dial: "61", primary: true },
  { code: "AT", name: "Austria", dial: "43", primary: true },
  { code: "AZ", name: "Azerbaijan", dial: "994", primary: true },
  { code: "BS", name: "Bahamas", dial: "1" },
  { code: "BH", name: "Bahrain", dial: "973", primary: true },
  { code: "BD", name: "Bangladesh", dial: "880", primary: true },
  { code: "BB", name: "Barbados", dial: "1" },
  { code: "BY", name: "Belarus", dial: "375", primary: true },
  { code: "BE", name: "Belgium", dial: "32", primary: true },
  { code: "BZ", name: "Belize", dial: "501", primary: true },
  { code: "BJ", name: "Benin", dial: "229", primary: true },
  { code: "BM", name: "Bermuda", dial: "1" },
  { code: "BT", name: "Bhutan", dial: "975", primary: true },
  { code: "BO", name: "Bolivia", dial: "591", primary: true },
  { code: "BA", name: "Bosnia & Herzegovina", dial: "387", primary: true },
  { code: "BW", name: "Botswana", dial: "267", primary: true },
  { code: "BR", name: "Brazil", dial: "55", primary: true },
  { code: "BN", name: "Brunei", dial: "673", primary: true },
  { code: "BG", name: "Bulgaria", dial: "359", primary: true },
  { code: "BF", name: "Burkina Faso", dial: "226", primary: true },
  { code: "BI", name: "Burundi", dial: "257", primary: true },
  { code: "KH", name: "Cambodia", dial: "855", primary: true },
  { code: "CM", name: "Cameroon", dial: "237", primary: true },
  { code: "CA", name: "Canada", dial: "1" },
  { code: "CV", name: "Cape Verde", dial: "238", primary: true },
  { code: "KY", name: "Cayman Islands", dial: "1" },
  { code: "CF", name: "Central African Republic", dial: "236", primary: true },
  { code: "TD", name: "Chad", dial: "235", primary: true },
  { code: "CL", name: "Chile", dial: "56", primary: true },
  { code: "CN", name: "China", dial: "86", primary: true },
  { code: "CO", name: "Colombia", dial: "57", primary: true },
  { code: "KM", name: "Comoros", dial: "269", primary: true },
  { code: "CG", name: "Congo - Brazzaville", dial: "242", primary: true },
  { code: "CD", name: "Congo - Kinshasa", dial: "243", primary: true },
  { code: "CR", name: "Costa Rica", dial: "506", primary: true },
  { code: "CI", name: "Côte d’Ivoire", dial: "225", primary: true },
  { code: "HR", name: "Croatia", dial: "385", primary: true },
  { code: "CU", name: "Cuba", dial: "53", primary: true },
  { code: "CY", name: "Cyprus", dial: "357", primary: true },
  { code: "CZ", name: "Czechia", dial: "420", primary: true },
  { code: "DK", name: "Denmark", dial: "45", primary: true },
  { code: "DJ", name: "Djibouti", dial: "253", primary: true },
  { code: "DM", name: "Dominica", dial: "1" },
  { code: "DO", name: "Dominican Republic", dial: "1" },
  { code: "EC", name: "Ecuador", dial: "593", primary: true },
  { code: "EG", name: "Egypt", dial: "20", primary: true },
  { code: "SV", name: "El Salvador", dial: "503", primary: true },
  { code: "GQ", name: "Equatorial Guinea", dial: "240", primary: true },
  { code: "ER", name: "Eritrea", dial: "291", primary: true },
  { code: "EE", name: "Estonia", dial: "372", primary: true },
  { code: "SZ", name: "Eswatini", dial: "268", primary: true },
  { code: "ET", name: "Ethiopia", dial: "251", primary: true },
  { code: "FJ", name: "Fiji", dial: "679", primary: true },
  { code: "FI", name: "Finland", dial: "358", primary: true },
  { code: "FR", name: "France", dial: "33", primary: true },
  { code: "PF", name: "French Polynesia", dial: "689", primary: true },
  { code: "GA", name: "Gabon", dial: "241", primary: true },
  { code: "GM", name: "Gambia", dial: "220", primary: true },
  { code: "GE", name: "Georgia", dial: "995", primary: true },
  { code: "DE", name: "Germany", dial: "49", primary: true },
  { code: "GH", name: "Ghana", dial: "233", primary: true },
  { code: "GI", name: "Gibraltar", dial: "350", primary: true },
  { code: "GR", name: "Greece", dial: "30", primary: true },
  { code: "GL", name: "Greenland", dial: "299", primary: true },
  { code: "GD", name: "Grenada", dial: "1" },
  { code: "GU", name: "Guam", dial: "1" },
  { code: "GT", name: "Guatemala", dial: "502", primary: true },
  { code: "GN", name: "Guinea", dial: "224", primary: true },
  { code: "GW", name: "Guinea-Bissau", dial: "245", primary: true },
  { code: "GY", name: "Guyana", dial: "592", primary: true },
  { code: "HT", name: "Haiti", dial: "509", primary: true },
  { code: "HN", name: "Honduras", dial: "504", primary: true },
  { code: "HK", name: "Hong Kong SAR", dial: "852", primary: true },
  { code: "HU", name: "Hungary", dial: "36", primary: true },
  { code: "IS", name: "Iceland", dial: "354", primary: true },
  { code: "IN", name: "India", dial: "91", primary: true },
  { code: "ID", name: "Indonesia", dial: "62", primary: true },
  { code: "IR", name: "Iran", dial: "98", primary: true },
  { code: "IQ", name: "Iraq", dial: "964", primary: true },
  { code: "IE", name: "Ireland", dial: "353", primary: true },
  { code: "IL", name: "Israel", dial: "972", primary: true },
  { code: "IT", name: "Italy", dial: "39", primary: true },
  { code: "JM", name: "Jamaica", dial: "1" },
  { code: "JP", name: "Japan", dial: "81", primary: true },
  { code: "JO", name: "Jordan", dial: "962", primary: true },
  { code: "KZ", name: "Kazakhstan", dial: "7" },
  { code: "KE", name: "Kenya", dial: "254", primary: true },
  { code: "KI", name: "Kiribati", dial: "686", primary: true },
  { code: "XK", name: "Kosovo", dial: "383", primary: true },
  { code: "KW", name: "Kuwait", dial: "965", primary: true },
  { code: "KG", name: "Kyrgyzstan", dial: "996", primary: true },
  { code: "LA", name: "Laos", dial: "856", primary: true },
  { code: "LV", name: "Latvia", dial: "371", primary: true },
  { code: "LB", name: "Lebanon", dial: "961", primary: true },
  { code: "LS", name: "Lesotho", dial: "266", primary: true },
  { code: "LR", name: "Liberia", dial: "231", primary: true },
  { code: "LY", name: "Libya", dial: "218", primary: true },
  { code: "LI", name: "Liechtenstein", dial: "423", primary: true },
  { code: "LT", name: "Lithuania", dial: "370", primary: true },
  { code: "LU", name: "Luxembourg", dial: "352", primary: true },
  { code: "MO", name: "Macao SAR", dial: "853", primary: true },
  { code: "MG", name: "Madagascar", dial: "261", primary: true },
  { code: "MW", name: "Malawi", dial: "265", primary: true },
  { code: "MY", name: "Malaysia", dial: "60", primary: true },
  { code: "MV", name: "Maldives", dial: "960", primary: true },
  { code: "ML", name: "Mali", dial: "223", primary: true },
  { code: "MT", name: "Malta", dial: "356", primary: true },
  { code: "MH", name: "Marshall Islands", dial: "692", primary: true },
  { code: "MR", name: "Mauritania", dial: "222", primary: true },
  { code: "MU", name: "Mauritius", dial: "230", primary: true },
  { code: "MX", name: "Mexico", dial: "52", primary: true },
  { code: "FM", name: "Micronesia", dial: "691", primary: true },
  { code: "MD", name: "Moldova", dial: "373", primary: true },
  { code: "MC", name: "Monaco", dial: "377", primary: true },
  { code: "MN", name: "Mongolia", dial: "976", primary: true },
  { code: "ME", name: "Montenegro", dial: "382", primary: true },
  { code: "MA", name: "Morocco", dial: "212", primary: true },
  { code: "MZ", name: "Mozambique", dial: "258", primary: true },
  { code: "MM", name: "Myanmar", dial: "95", primary: true },
  { code: "NA", name: "Namibia", dial: "264", primary: true },
  { code: "NR", name: "Nauru", dial: "674", primary: true },
  { code: "NP", name: "Nepal", dial: "977", primary: true },
  { code: "NL", name: "Netherlands", dial: "31", primary: true },
  { code: "NC", name: "New Caledonia", dial: "687", primary: true },
  { code: "NZ", name: "New Zealand", dial: "64", primary: true },
  { code: "NI", name: "Nicaragua", dial: "505", primary: true },
  { code: "NE", name: "Niger", dial: "227", primary: true },
  { code: "NG", name: "Nigeria", dial: "234", primary: true },
  { code: "KP", name: "North Korea", dial: "850", primary: true },
  { code: "MK", name: "North Macedonia", dial: "389", primary: true },
  { code: "NO", name: "Norway", dial: "47", primary: true },
  { code: "OM", name: "Oman", dial: "968", primary: true },
  { code: "PK", name: "Pakistan", dial: "92", primary: true },
  { code: "PW", name: "Palau", dial: "680", primary: true },
  { code: "PS", name: "Palestine", dial: "970", primary: true },
  { code: "PA", name: "Panama", dial: "507", primary: true },
  { code: "PG", name: "Papua New Guinea", dial: "675", primary: true },
  { code: "PY", name: "Paraguay", dial: "595", primary: true },
  { code: "PE", name: "Peru", dial: "51", primary: true },
  { code: "PH", name: "Philippines", dial: "63", primary: true },
  { code: "PL", name: "Poland", dial: "48", primary: true },
  { code: "PT", name: "Portugal", dial: "351", primary: true },
  { code: "PR", name: "Puerto Rico", dial: "1" },
  { code: "QA", name: "Qatar", dial: "974", primary: true },
  { code: "RO", name: "Romania", dial: "40", primary: true },
  { code: "RU", name: "Russia", dial: "7", primary: true },
  { code: "RW", name: "Rwanda", dial: "250", primary: true },
  { code: "WS", name: "Samoa", dial: "685", primary: true },
  { code: "SM", name: "San Marino", dial: "378", primary: true },
  { code: "SA", name: "Saudi Arabia", dial: "966", primary: true },
  { code: "SN", name: "Senegal", dial: "221", primary: true },
  { code: "RS", name: "Serbia", dial: "381", primary: true },
  { code: "SC", name: "Seychelles", dial: "248", primary: true },
  { code: "SL", name: "Sierra Leone", dial: "232", primary: true },
  { code: "SG", name: "Singapore", dial: "65", primary: true },
  { code: "SK", name: "Slovakia", dial: "421", primary: true },
  { code: "SI", name: "Slovenia", dial: "386", primary: true },
  { code: "SB", name: "Solomon Islands", dial: "677", primary: true },
  { code: "SO", name: "Somalia", dial: "252", primary: true },
  { code: "ZA", name: "South Africa", dial: "27", primary: true },
  { code: "KR", name: "South Korea", dial: "82", primary: true },
  { code: "SS", name: "South Sudan", dial: "211", primary: true },
  { code: "ES", name: "Spain", dial: "34", primary: true },
  { code: "LK", name: "Sri Lanka", dial: "94", primary: true },
  { code: "KN", name: "St. Kitts & Nevis", dial: "1" },
  { code: "LC", name: "St. Lucia", dial: "1" },
  { code: "VC", name: "St. Vincent & Grenadines", dial: "1" },
  { code: "SD", name: "Sudan", dial: "249", primary: true },
  { code: "SR", name: "Suriname", dial: "597", primary: true },
  { code: "SE", name: "Sweden", dial: "46", primary: true },
  { code: "CH", name: "Switzerland", dial: "41", primary: true },
  { code: "SY", name: "Syria", dial: "963", primary: true },
  { code: "TW", name: "Taiwan", dial: "886", primary: true },
  { code: "TJ", name: "Tajikistan", dial: "992", primary: true },
  { code: "TZ", name: "Tanzania", dial: "255", primary: true },
  { code: "TH", name: "Thailand", dial: "66", primary: true },
  { code: "TL", name: "Timor-Leste", dial: "670", primary: true },
  { code: "TG", name: "Togo", dial: "228", primary: true },
  { code: "TO", name: "Tonga", dial: "676", primary: true },
  { code: "TT", name: "Trinidad & Tobago", dial: "1" },
  { code: "TN", name: "Tunisia", dial: "216", primary: true },
  { code: "TR", name: "Türkiye", dial: "90", primary: true },
  { code: "TM", name: "Turkmenistan", dial: "993", primary: true },
  { code: "TV", name: "Tuvalu", dial: "688", primary: true },
  { code: "UG", name: "Uganda", dial: "256", primary: true },
  { code: "UA", name: "Ukraine", dial: "380", primary: true },
  { code: "AE", name: "United Arab Emirates", dial: "971", primary: true },
  { code: "GB", name: "United Kingdom", dial: "44", primary: true },
  { code: "US", name: "United States", dial: "1", primary: true },
  { code: "UY", name: "Uruguay", dial: "598", primary: true },
  { code: "UZ", name: "Uzbekistan", dial: "998", primary: true },
  { code: "VU", name: "Vanuatu", dial: "678", primary: true },
  { code: "VE", name: "Venezuela", dial: "58", primary: true },
  { code: "VN", name: "Vietnam", dial: "84", primary: true },
  { code: "YE", name: "Yemen", dial: "967", primary: true },
  { code: "ZM", name: "Zambia", dial: "260", primary: true },
  { code: "ZW", name: "Zimbabwe", dial: "263", primary: true },
];

const BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));

/** Dial codes longest-first, so parsing matches "+1868" before "+1". */
const DIALS_BY_LENGTH = [...COUNTRIES].sort((a, b) => b.dial.length - a.dial.length);

/** Look up a country by ISO 3166-1 alpha-2 code. */
export function countryByCode(code: string | null | undefined): Country | undefined {
  return code ? BY_CODE.get(code.toUpperCase()) : undefined;
}

/** Dial code for an ISO code, e.g. "IN" -> "91". Falls back to the US ("1"). */
export function dialCodeFor(code: string | null | undefined): string {
  return countryByCode(code)?.dial ?? "1";
}

/**
 * The country a stored E.164 number belongs to, by longest-matching dial code.
 * Shared codes resolve to the `primary` country (see {@link Country.primary}).
 */
export function countryForE164(value: string | null | undefined): Country | undefined {
  if (!value) return undefined;
  const digits = value.trim().replace(/[^\d+]/g, "");
  if (!digits.startsWith("+")) return undefined;
  const national = digits.slice(1);
  for (const c of DIALS_BY_LENGTH) {
    if (!national.startsWith(c.dial)) continue;
    return COUNTRIES.find((o) => o.dial === c.dial && o.primary) ?? c;
  }
  return undefined;
}

/**
 * ISO code guessed from an IANA timezone, so a phone field opens on the user's
 * own country instead of always on the US. Unknown zones return undefined and
 * the caller keeps its own default.
 */
export function countryCodeForTimeZone(zone: string | null | undefined): string | undefined {
  return zone ? COUNTRY_BY_TIMEZONE[zone] : undefined;
}

const COUNTRY_BY_TIMEZONE: Record<string, string> = {
  "Africa/Abidjan": "CI",
  "Africa/Accra": "GH",
  "Africa/Addis_Ababa": "ET",
  "Africa/Algiers": "DZ",
  "Africa/Cairo": "EG",
  "Africa/Casablanca": "MA",
  "Africa/Dar_es_Salaam": "TZ",
  "Africa/Johannesburg": "ZA",
  "Africa/Kampala": "UG",
  "Africa/Khartoum": "SD",
  "Africa/Kinshasa": "CD",
  "Africa/Lagos": "NG",
  "Africa/Luanda": "AO",
  "Africa/Lusaka": "ZM",
  "Africa/Nairobi": "KE",
  "Africa/Tripoli": "LY",
  "Africa/Tunis": "TN",
  "America/Anchorage": "US",
  "America/Argentina/Buenos_Aires": "AR",
  "America/Bogota": "CO",
  "America/Caracas": "VE",
  "America/Chicago": "US",
  "America/Costa_Rica": "CR",
  "America/Denver": "US",
  "America/Edmonton": "CA",
  "America/Guatemala": "GT",
  "America/Halifax": "CA",
  "America/Havana": "CU",
  "America/Jamaica": "JM",
  "America/Lima": "PE",
  "America/Los_Angeles": "US",
  "America/Mexico_City": "MX",
  "America/Montevideo": "UY",
  "America/New_York": "US",
  "America/Panama": "PA",
  "America/Phoenix": "US",
  "America/Puerto_Rico": "PR",
  "America/Santiago": "CL",
  "America/Santo_Domingo": "DO",
  "America/Sao_Paulo": "BR",
  "America/St_Johns": "CA",
  "America/Toronto": "CA",
  "America/Vancouver": "CA",
  "America/Winnipeg": "CA",
  "Asia/Almaty": "KZ",
  "Asia/Amman": "JO",
  "Asia/Baghdad": "IQ",
  "Asia/Baku": "AZ",
  "Asia/Bangkok": "TH",
  "Asia/Beirut": "LB",
  "Asia/Colombo": "LK",
  "Asia/Dhaka": "BD",
  "Asia/Dubai": "AE",
  "Asia/Ho_Chi_Minh": "VN",
  "Asia/Hong_Kong": "HK",
  "Asia/Jakarta": "ID",
  "Asia/Jerusalem": "IL",
  "Asia/Kabul": "AF",
  "Asia/Karachi": "PK",
  "Asia/Kathmandu": "NP",
  "Asia/Kolkata": "IN",
  "Asia/Kuala_Lumpur": "MY",
  "Asia/Kuwait": "KW",
  "Asia/Manila": "PH",
  "Asia/Muscat": "OM",
  "Asia/Qatar": "QA",
  "Asia/Riyadh": "SA",
  "Asia/Seoul": "KR",
  "Asia/Shanghai": "CN",
  "Asia/Singapore": "SG",
  "Asia/Taipei": "TW",
  "Asia/Tashkent": "UZ",
  "Asia/Tbilisi": "GE",
  "Asia/Tehran": "IR",
  "Asia/Tokyo": "JP",
  "Asia/Yangon": "MM",
  "Asia/Yerevan": "AM",
  "Atlantic/Reykjavik": "IS",
  "Australia/Adelaide": "AU",
  "Australia/Brisbane": "AU",
  "Australia/Melbourne": "AU",
  "Australia/Perth": "AU",
  "Australia/Sydney": "AU",
  "Europe/Amsterdam": "NL",
  "Europe/Athens": "GR",
  "Europe/Belgrade": "RS",
  "Europe/Berlin": "DE",
  "Europe/Bratislava": "SK",
  "Europe/Brussels": "BE",
  "Europe/Bucharest": "RO",
  "Europe/Budapest": "HU",
  "Europe/Copenhagen": "DK",
  "Europe/Dublin": "IE",
  "Europe/Helsinki": "FI",
  "Europe/Istanbul": "TR",
  "Europe/Kyiv": "UA",
  "Europe/Lisbon": "PT",
  "Europe/Ljubljana": "SI",
  "Europe/London": "GB",
  "Europe/Madrid": "ES",
  "Europe/Moscow": "RU",
  "Europe/Oslo": "NO",
  "Europe/Paris": "FR",
  "Europe/Prague": "CZ",
  "Europe/Rome": "IT",
  "Europe/Sofia": "BG",
  "Europe/Stockholm": "SE",
  "Europe/Tallinn": "EE",
  "Europe/Vienna": "AT",
  "Europe/Vilnius": "LT",
  "Europe/Warsaw": "PL",
  "Europe/Zagreb": "HR",
  "Europe/Zurich": "CH",
  "Pacific/Auckland": "NZ",
  "Pacific/Fiji": "FJ",
  "Pacific/Honolulu": "US",
};
