/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-person`; params?: Router.UnknownInputParams; } | { pathname: `/calendar-sync`; params?: Router.UnknownInputParams; } | { pathname: `/import`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/ring-preview`; params?: Router.UnknownInputParams; } | { pathname: `/widget-preview`; params?: Router.UnknownInputParams; } | { pathname: `/../../scripts/widget-check`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lists` | `/lists`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reminders` | `/reminders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/invite/[token]`, params: Router.UnknownInputParams & { token: string | number; } } | { pathname: `/list/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/person/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-person`; params?: Router.UnknownOutputParams; } | { pathname: `/calendar-sync`; params?: Router.UnknownOutputParams; } | { pathname: `/import`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/ring-preview`; params?: Router.UnknownOutputParams; } | { pathname: `/widget-preview`; params?: Router.UnknownOutputParams; } | { pathname: `/../../scripts/widget-check`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/lists` | `/lists`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reminders` | `/reminders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/invite/[token]`, params: Router.UnknownOutputParams & { token: string; } } | { pathname: `/list/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/person/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-person${`?${string}` | `#${string}` | ''}` | `/calendar-sync${`?${string}` | `#${string}` | ''}` | `/import${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/ring-preview${`?${string}` | `#${string}` | ''}` | `/widget-preview${`?${string}` | `#${string}` | ''}` | `/../../scripts/widget-check${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/lists${`?${string}` | `#${string}` | ''}` | `/lists${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reminders${`?${string}` | `#${string}` | ''}` | `/reminders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-person`; params?: Router.UnknownInputParams; } | { pathname: `/calendar-sync`; params?: Router.UnknownInputParams; } | { pathname: `/import`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/ring-preview`; params?: Router.UnknownInputParams; } | { pathname: `/widget-preview`; params?: Router.UnknownInputParams; } | { pathname: `/../../scripts/widget-check`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/lists` | `/lists`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reminders` | `/reminders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/invite/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/list/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/person/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/invite/[token]`, params: Router.UnknownInputParams & { token: string | number; } } | { pathname: `/list/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/person/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
